spring.application.name=${SPRING_APPLICATION_NAME}

server.port=${SERVER_PORT}

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# MQTT
mqtt.broker=${MQTT_BROKER}
mqtt.client-id=${MQTT_CLIENT_ID}
mqtt.topic=${MQTT_TOPICS:greenhouse/sensor/register,greenhouse/sensor/data}

sensor.online.timeout.minutes=${SENSOR_ONLINE_TIMEOUT_MINUTES}

management.endpoints.web.exposure.include=*

logging.level.org.springframework.web.socket=TRACE
logging.level.org.springframework.web.socket.config=TRACE
logging.level.org.springframework.messaging=TRACE